import {
  IconLayout,
  IconUserCheck,
  IconSchool,
  IconCalendar,
  IconBook,
  IconUsers,
  IconUserCog,
  IconShield,
  IconClipboardList,
  IconClock,
  IconCreditCard,
  IconChartHistogram,
  IconSettings,
  IconDownload,
  IconDeviceLaptop,
  IconDeviceImacUp,
  IconAlertCircle,
  IconFileDescription,
  IconMessage,
  IconServerBolt,
  IconUsersGroup,
  IconCurrencyDollar,
  IconChartInfographic,
  IconNotebook,
  IconTrendingUp,
  IconWallet,
  IconChalkboardTeacher,
  IconFileCertificate,
  IconFileText,
  IconHome,
  IconChartBarPopular,
  IconArticle,
  IconShoppingCart,
  IconInfoCircle,
  IconTrophy,
  IconNews,
  IconBrandCodecov,
  IconStackMiddle,
  IconBriefcase,
  IconShoppingBag,
  IconMail,
} from "@tabler/icons-react";

export const homeNavLinks = [
  { slug: "/", label: "Home", icon: IconHome },
  { slug: "/about", label: "About", icon: IconInfoCircle },
  { slug: "/innovation", label: "Innovation", icon: IconBrandCodecov },
  { slug: "/solutions", label: "Solutions", icon: IconServerBolt },
  { slug: "/sustainability", label: "Sustainability", icon: IconStackMiddle },
];

export const PHONE_NUMBER = "+234 (0) 123 456 7890";
export const ADDRESS = "Lagos, Nigeria";
export const HERO_VIDEO = "https://airmob.t3.storage.dev/hero.mp4";
